- name: Remove existing code
  ansible.builtin.file:
    path: "{{APP_LOC}}"
    state: absent
  when: APP_TYPE == "frontend" or APP_TYPE == "backend"

- name: Create App code directory
  ansible.builtin.file:
    path: "{{APP_LOC}}"
    state: directory
  when: APP_TYPE == "frontend" or APP_TYPE == "backend"
  become_user: roboshop

- name: Download App Component
  get_url:
    url: http://172.31.16.46:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /tmp/{{COMPONENT}}.zip
    url_username: "{{NEXUS_USER}}"
    url_password: "{{NEXUS_PASS}}"

- name: Extract {{COMPONENT}} Code
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: "{{APP_LOC}}"
    remote_src: yes
  become_user: roboshop
