- name: Download {{COMPONENT}} Code
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Remove existing code
  ansible.builtin.file:
    path: "{{APP_LOC}}"
    state: absent
  when: APP_TYPE == "frontend" or APP_TYPE == "backend"

- name: Copy App Code
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: "{{APP_LOC}}"
    remote_src: yes
  become_user: "{{APP_USER}}"
  when: APP_TYPE == "backend"

- name: Copy App code from GIT
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes
  when: APP_TYPE == "frontend"