- name: Download and Unarchive app files for {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp/
    remote_src: yes

- name: Recursively remove existing directory content
  ansible.builtin.file:
    path: "{{APP_LOC}}"
    state: absent

- name: copy code to app location
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: "{{APP_LOC}}"
    remote_src: yes
  when: APP_TYPE == "backend"
  become_user: APP_USER