- name: Include Download from GitHub
  include_tasks: download-from-github.yml
  when: APP_VERSION == ""

- name: Include Download from Nexus
  include_tasks: download-from-nexus.yml
  when: APP_VERSION != ""
