- name: Setting hostname
  ansible.builtin.shell:
    cmd: set-hostname {{COMPONENT}}

- name: Install required utilities
  ansible.builtin.yum:
    name:
      - epel-release
      - yum-utils
    state: present

- name: Install redis repos
  ansible.builtin.yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    enablerepo: remi

- name: Update Redis Listen address
  replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Update Redis Listen address
  replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes
