{{- if .Values.configmap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "roboshop.labels" . | nindent 4 }}
data:
  {{- with .Values.configmap.content }}
    {{- toYaml . | nindent 2 }}
    {{- end }}
  {{- end }}
