- name: Setting hostname
  ansible.builtin.shell:
    cmd: set-hostname {{COMPONENT}}

- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: present

- name: create app user roboshop
  ansible.builtin.include_role:
    name: common
    tasks_from: app_user

- name: Download code
  ansible.builtin.include_role:
    name: common
    tasks_from: download
  vars:
    APP_LOC: /home/roboshop/{{COMPONENT}}
    APP_USER: roboshop

- name: Clean Maven existing info
  ansible.builtin.shell:
    cmd: mvn clean package
    chdir: /home/roboshop/shipping/
  become_user: roboshop

- name: Copy shipping.jar file
  ansible.builtin.copy:
    src: /home/roboshop/shipping/target/shipping-1.0.jar
    dest: /home/roboshop/shipping/shipping.jar
    remote_src: yes
  become_user: roboshop

- name: Removing shipping-1.0.jar file
  ansible.builtin.file:
    path: /home/roboshop/shipping/target/shipping-1.0.jar
    state: absent

- name: systemd service configuration and restart
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd