- name: Setting hostname
  ansible.builtin.shell:
    cmd: set-hostname {{COMPONENT}}

- name: Install the latest version of Nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Download code
  include_role:
    name: common
    tasks_from: download

- name: Copy Roboshob config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes
    daemon_reload: yes
  when: AMI is not defined

- name: Enable Nginx Service
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
  when: AMI is defined

#- name: Recursively remove directory
#  ansible.builtin.file:
#    path: /tmp/frontend-main
#    state: absent

- name: Setup Node Exporter
  ansible.builtin.include_role:
    name: node-exporter