[frontend]
frontend-dev.roboshop.internal
[cart]
cart-dev.roboshop.internal
[catalogue]
catalogue-dev.roboshop.internal
[payment]
payment-dev.roboshop.internal
[shipping]
shipping-dev.roboshop.internal
[mysql]
mysql-dev.roboshop.internal
[mongodb]
mongodb-dev.roboshop.internal
[redis]
redis-dev.roboshop.internal
[rabbitmq]
rabbitmq-dev.roboshop.internal
[user]
user-dev.roboshop.internal
