- name: Setting hostname
  ansible.builtin.shell:
    cmd: set-hostname {{COMPONENT}}

- name: Download mysql repo file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/roboshop-devops-project/mysql/main/mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Removing mariadb libraries(Since, mariadb related things are not required)
  ansible.builtin.yum:
    name: mariadb-libs
    state: absent

- name: Install MySQL
  ansible.builtin.yum:
    name:
    - mysql-community-server
    - python36-PyMySQL.noarch
    - MySQL-python.x86_64
    state: present

- name: Restart mysqld service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Getting default root password
  ansible.builtin.shell:
    cmd: cat /var/log/mysqld.log|grep "A temporary password"|awk '{print $NF}'
  register: defaultpass

- name: Check whether password was already set to new password
  ansible.builtin.shell:
    cmd: echo 'show databases;'|mysql -uroot -p{{NEW_PASSWORD}}
  ignore_errors: yes
  register: check_new_pass

- name: Copy Password reset sql file
  ansible.builtin.template:
    src: pass.sql
    dest: /tmp/pass.sql
  when: check_new_pass.failed

- name: Change the password to new password
  ansible.builtin.shell:
    cmd: mysql --connect-expired-password -uroot -p"{{defaultpass.stdout}}" < /tmp/pass.sql
  when: check_new_pass.failed

- name: Download MySQL schema
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Load MySQL schema
  community.mysql.mysql_db:
    state: import
    login_user: root
    login_password: "{{NEW_PASSWORD}}"
    name: all
    target: /tmp/mysql-main/shipping.sql


#- name: Set MySQL root password
#  community.mysql.mysql_user:
#    login_host: 'localhost'
#    login_user: 'root'
#    login_password: "{{defaultpass.stdout}}"
#    name: 'root'
#    password: DevOps321
#    state: present

