- name: Deploy frontend
  hosts: frontend
  become: true
  tags: frontend
  roles:
    - frontend

- name: Deploy catalogue
  hosts: catalogue
  become: true
  tags: catalogue
  roles:
    - catalogue

- name: Deploy mongodb
  hosts: mongodb
  become: true
  tags: mongodb
  roles:
    - mongodb

- name: Deploy Cart
  hosts: cart
  become: true
  tags: cart
  roles:
    - cart