- name: Deploy frontend
  hosts: frontend
  become: true
  tags: frontend
  roles:
    - frontend

- name: Deploy catalogue
  hosts: catalogue
  become: true
  tags: catalogue
  roles:
    - catalogue