filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - {{LOG_FILE}}
    fields:
      app: {{COMPONENT}}
      env: {{ENV}}
  {% if LOG_TYPE == "json" %}
json.keys_under_root: true
  {% endif %}
  {% if MULTILINE_TYPE == "java" %}
multiline.pattern: "^[0-9][0-9][0-9][0-9]"
multiline.negate: true
multiline.match: after
  {% endif %}

  {% if INCLUDE_LINES == "python" %}
include_lines: ['^\[2']
  {% endif %}

output.logstash:
  hosts: ["logstash.roboshop.internal:5044"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
