filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - {{LOG_FILE}}

output.logstash:
  hosts: ["logstash.knowaws.com:5044"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
