- name: Setting hostname
  ansible.builtin.shell:
    cmd: set-hostname {{COMPONENT}}

- name: Download mongodb repo file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/roboshop-devops-project/mongodb/main/mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: present

- name: Change Listen address to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restart mongod service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Download mongodb schema
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: load schema(.js file) to mongodb
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users
