- name: Copy Prometheus Config
  template:
    src: "{{item}}.yml"
    dest: /opt/prometheus/{{item}}.yml
  loop:
    - alerts
    - prometheus
    - records

- name: Restart prometheus
  systemd:
    name: prometheus
    state: restarted

- name: Copy Alert Manager Config
  template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart alertmanager
  systemd:
    name: alertmanager
    state: restarted
